export const FETCH_LOGIN_USERNAME = 'FETCH_LOGIN_USERNAME';
export const FETCH_LOGIN_TYPE = 'FETCH_LOGIN_TYPE';

export const FETCH_USER_INFO = 'FETCH_USER_INFO';

export const FETCH_ALL_PRODUCT = 'FETCH_ALL_PRODUCT';

export const FETCH_CART_DETAIL = 'FETCH_CART_DETAIL';

export const FETCH_ORDER_LIST = 'FETCH_ORDER_LIST';

export const FETCH_ACCOUNT_LIST = 'FETCH_ACCOUNT_LIST';